### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Upgraded Continous Integration.

For details see commit list.

@yoitsro : I can set up codeclimate and coverage if you are open to this.

Also dropping 0.10 to use latest deps, and release a new major would be a good thing I think :)

### CODE REVIEW

**Comment by yoitsro** [comment]
Hey @AdrieanKhisbe. Thanks so much for this! It's greatly appreciated. I've had a quick look, but will have a deeper look tomorrow.

**Comment by AdrieanKhisbe** [comment]
You're welcome :)

Keep me posted for the [coverage](http://coveralls.io) and [climate](http://codeclimate.com) ;)

**Comment by AdrieanKhisbe** [comment]
Hello @yoitsro, did you have time to give a look? :)

Here is a snippet what codeclimate and coveralls can give:
- https://codeclimate.com/github/AdrieanKhisbe/configue/code?q=rating%3AA
- https://coveralls.io/github/AdrieanKhisbe/hapi-configue

**Comment by yoitsro** [comment]
Go for it! Set it up :)

**Comment by AdrieanKhisbe** [comment]
noted, incoming in the coming days :)

**Pull request merged**
