### PR TITLE
feat: wrap the API under the _mongoose key

### PR DESCRIPTION
**Pull request by g-div**
e.g. `.meta({ _mongoose: { type: "ObjectId" } })`
see #15

### CODE REVIEW

**Comment by yoitsro** [comment]
Nice! Once again, thanks for this :)

Please could you try to increase the code coverage? https://travis-ci.org/yoitsro/joigoose/jobs/623710802#L227

**Comment by g-div** [comment]
Restored to the previous coverage level ;)

**Comment by yoitsro** [comment]
Ha! Nice! How would you feel about getting those last three lines?  🎯

**Comment by g-div** [comment]
Can't catch [L200](https://github.com/yoitsro/joigoose/pull/33/files#diff-6d186b954a58d5bb740f73d84fe39073R200). Is it probably because isn't anymore possible to pass an array to [`.items(...types)`](https://hapi.dev/family/joi/?v=16.1.8#arrayitemstypes) ?

**Comment by yoitsro** [comment]
Okay, cool. I guess we can just drop that check :) 🎉

**Comment by g-div** [comment]
I'm not sure, but I believe we can even drop that line and get 100% coverage

**Comment by yoitsro** [comment]
We can - I did a check and if you try to use an array, it throws an error.

**Comment by g-div** [comment]
:100::rocket:

**Comment by g-div** [comment]
Don't you like it ? I think some lines are much more readable, specially loops. If you don't, I can eventually revert it.

**Comment by yoitsro** [comment]
Niiice! Next thing: should I release this as _another_ breaking change?

**Comment by g-div** [comment]
Theoretically the ES6 refactor and the meta API changes can be in the same release, e.g. 6.0.0

**Comment by g-div** [comment]
My concern is also that this PR won't completely fix #33, but the future work can be in v6.x

**Comment by yoitsro** [comment]
Sorry, I meant this commit would be a breaking change: https://github.com/yoitsro/joigoose/pull/33/commits/766b04a154d844d8d093d74e5444e959103b4aaf

The rest, I'd be comfortable merging into 5.x.x. 5.x.x is a new release as of today since it's built against a completely different version of joi.

If we merged your original commit in, since the adoption of version 5 is still likely to be relatively low, could we get away with merging this into version 5 too?

**Comment by g-div** [comment]
Yes, I also think this shouldn't be a problem, but if you want to be sure then you should maybe release a 6.x.x verion

**Comment by yoitsro** [comment]
I'm going to risk it 🤷‍♂. If anyone has any issues, I'm sure I'll hear about it 🙃

**Pull request merged**
