### PR TITLE
Pass the error from Joi into the mongoose validator

### PR DESCRIPTION
**Pull request by kjanoudi**
This will pass back the error from joi into the mongoose validator

### CODE REVIEW

**Comment by kjanoudi** [comment]
#6

**Comment by yoitsro** [comment]
Hey @kjanoudi! Thanks for this! Would you mind adding a test and updating the broken tests for this too please?

**Comment by kjanoudi** [comment]
@yoitsro all set, thanks!

**Comment by kjanoudi** [comment]
@yoitsro hello?

**Comment by yoitsro** [comment]
@kjanoudi hey! Sorry about the delay. It's been a busy, busy week! I'm just thinking about what kind of release this should be - major, minor or bugfix. I feel like this is a major change, on account of if people are relying on certain error messages on what's currently released, this will break that.

What do you think?

**Comment by kjanoudi** [comment]
@yoitsro Yeah. I tend to agree. Do you think there's an alternative to a breaking change that gives us what we need?

**Comment by yoitsro** [comment]
We could add a flag somewhere, but it feels messy. I like the change, but just don't want to break people's stuff. I'd be happy to do a major release.

**Comment by kjanoudi** [comment]
That works for me. For a major release perhaps we can return error objects rather than just the strings built in this way. I'd have to look at it closer, is that even possible with how mongoose handles errors?

**Comment by yoitsro** [comment]
Hey @kjanoudi. I've updated joigoose to be async/await. Please could you take a look at how you could modify your PR to accommodate these changes? I'm sorry that I've made such a big change before merging your stuff in!

**Comment by yoitsro** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
